-- luacheck configuration for WideQuestLogPlus (https://github.com/lunarmodules/luacheck)
std = "lua51"
max_line_length = false

-- Globals this addon deliberately writes (see the taint notes in the files that write them)
globals = {
	"WideQuestLogPlusDB", -- Saved variables
	"SLASH_WIDEQUESTLOGPLUS1",
	"SLASH_WIDEQUESTLOGPLUS2",
	"SlashCmdList",
	"ToggleQuestLog", -- WoW Forever: routed to the addon's quest log
	"QuestMapFrame_OpenToQuestDetails", -- WoW Forever: routed to the addon's quest log
	"QUESTS_DISPLAYED" -- Classic: more list rows in a taller quest log
}

-- WoW API, Blizzard UI and other addons' globals this addon reads
read_globals = {
	"QuestFontNormalSmall",
	"QuestLogMoneyFrame",
	"GetQuestLogLeaderBoard",
	"GetNumQuestLeaderBoards",
	"QuestInfoRewardsFrame",
	"QuestInfoObjectivesFrame",
	"QuestLogDescriptionTitle",
	"QuestLogItemChooseText",
	"QuestLogRewardTitleText",
	"QuestInfo_ShowDescriptionText",
	"QuestInfoFrame",
	"QuestLogObjectivesText",
	"QuestInfo_ShowObjectivesText",
	"QuestLogHighlightFrame",
	"QUESTLOG_QUEST_HEIGHT",
	"FauxScrollFrame_Update",
	"format", -- WoW's alias of string.format
	"ABANDON_QUEST",
	"ALL",
	"COMPLETE",
	"C_AddOns",
	"C_QuestLog",
	"C_Timer",
	"ChatFrameUtil",
	"CollapseQuestHeader",
	"Constants",
	"CopyTable",
	"CreateDataProvider",
	"CreateFrame",
	"CreateScrollBoxListLinearView",
	"ELITE",
	"EXIT",
	"EmptyQuestLogFrame",
	"ExpandQuestHeader",
	"FAILED",
	"FauxScrollFrame_GetOffset",
	"GameTooltip",
	"GameTooltip_Hide",
	"GetCursorPosition",
	"GetNumQuestLogEntries",
	"GetQuestDifficultyColor",
	"GetQuestLink",
	"GetQuestLogSelection",
	"GetQuestLogTitle",
	"GetQuestTagInfo",
	"HIGHLIGHT_FONT_COLOR_CODE",
	"IsAddOnLoaded",
	"IsCurrentQuestFailed",
	"IsInGroup",
	"IsMouseButtonDown",
	"IsShiftKeyDown",
	"MenuUtil",
	"OBJECTIVES_WATCH_TOO_MANY",
	"PARENS_TEMPLATE",
	"PlaySound",
	"QUESTLOG_NO_QUESTS_TEXT",
	"QUEST_LOG",
	"QUEST_LOG_COUNT_TEMPLATE",
	"QUEST_TEMPLATE_LOG",
	"QUEST_TITLE_FORMAT_FAILED",
	"QuestDifficultyColors",
	"QuestDifficultyHighlightColors",
	"QuestFrame",
	"QuestInfoDescriptionText",
	"QuestInfoTitleHeader",
	"QuestInfo_Display",
	"QuestInfo_ShowDescriptionHeader",
	"QuestInfo_ShowRewards",
	"QuestInfo_ShowSpacer",
	"QuestInfo_ShowTitle",
	"QuestLogDetailScrollChildFrame",
	"QuestLogDetailScrollFrame",
	"QuestLogFrame",
	"QuestLogItemReceiveText",
	"QuestLogListScrollFrame",
	"QuestLogNoQuestsText",
	"QuestLogPopupDetailFrame",
	"QuestLogQuestDescription",
	"QuestLogQuestTitle",
	"QuestLogSpacerFrame",
	"QuestLogSpellLearnText",
	"QuestLogTitle1",
	"QuestLogTitleText",
	"QuestLog_Update",
	"QuestMapFrame",
	"QuestMapQuestOptions_AbandonQuest",
	"QuestMapQuestOptions_ShareQuest",
	"QuestTextContrast",
	"QuestUtil",
	"QuestUtils_IsQuestWatched",
	"Questie",
	"QuestieLoader",
	"RED_FONT_COLOR_CODE",
	"SHARE_QUEST",
	"SOUNDKIT",
	"ScrollBoxConstants",
	"ScrollUtil",
	"SetUIPanelAttribute",
	"StaticPopup_Hide",
	"TRACK_QUEST",
	"TRACK_QUEST_ABBREV",
	"UIErrorsFrame",
	"UIParent",
	"UISpecialFrames",
	"UNTRACK_QUEST",
	"UNTRACK_QUEST_ABBREV",
	"_G",
	"hooksecurefunc",
	"strlower",
	"strtrim",
	"tinsert"
}
